[package]
name = "databend-common-storages-fuse"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
ahash = "0.8.3"
arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-ipc = { workspace = true }
async-backtrace = { workspace = true }
async-channel = "1.7.1"
async-trait = { workspace = true }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
bytes = { workspace = true }
chrono = { workspace = true }
databend-common-arrow = { workspace = true }
databend-common-base = { workspace = true }
databend-common-catalog = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-functions = { workspace = true }
databend-common-hashtable = { workspace = true }
databend-common-io = { workspace = true }
databend-common-license = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-metrics = { workspace = true }
databend-common-pipeline-core = { workspace = true }
databend-common-pipeline-sinks = { workspace = true }
databend-common-pipeline-sources = { workspace = true }
databend-common-pipeline-transforms = { workspace = true }
databend-common-sql = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-users = { workspace = true }
databend-enterprise-fail-safe = { workspace = true }
databend-storages-common-blocks = { workspace = true }
databend-storages-common-cache = { workspace = true }
databend-storages-common-index = { workspace = true }
databend-storages-common-io = { workspace = true }
databend-storages-common-pruner = { workspace = true }
databend-storages-common-session = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
enum-as-inner = "0.5"
fastrace = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
indexmap = "2.0.0"
itertools = { workspace = true }
jsonb = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
siphasher = "0.3.10"
sys-info = "0.9"
tantivy = { workspace = true }
tantivy-fst = "0.5"
tantivy-jieba = { git = "https://github.com/b41sh/tantivy-jieba", rev = "af84361" }
thrift = "0.17.0"
typetag = { workspace = true }
uuid = { workspace = true }
xorf = { version = "0.11.0", default-features = false, features = ["binary-fuse"] }

[dev-dependencies]
criterion = { workspace = true }

[lints]
workspace = true
